### ISSUE TITLE
Swiper images are not placed on centre

### ISSUE THREAD

**Issue by siketyan** [frouriojs/frourio.co.jp#3]
## Description

Images at the top of website which is placed by Swiper are not placed on centre.

Current Behaviour:
![image](https://user-images.githubusercontent.com/12772118/158061149-91b62e26-dcf9-4d97-9ead-1e0bff3d62c5.png)

Expected Behaviour:
![image](https://user-images.githubusercontent.com/12772118/158061171-10f6daeb-026b-4966-8289-ae7ed6afdbf4.png)

## Environment

- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS

## Additional context

- Browser:
  - 99.0.4844.51 (Official Build) (64-bit)

**Comment by ghost** [comment]
Thanks for issue 👍 but, this issue is not reproduce in my environment…
Result of my environment is below
<img width="1680" alt="Screen Shot 2022-03-14 at 10 07 19" src="https://user-images.githubusercontent.com/57579123/158088600-65a03df5-939e-4b4e-b24e-b10b606b52c0.png">

**Comment by ghost** [comment]
Please try clear a cache and force reload.

If still not work, please answer the questions below.
- What browser do you use?
